# application configuration
---
applicationName: userProfileSample
groupName: system
appUrl: 'http://localhost:8094'
appPath: '/pubsubUserProfileSample/'
icon: 'http://localhost:8082/pubsubUserProfile/logo/icon'
iconSmall: 'http://localhost:8082/pubsubUserProfile/logo/icon_small'
width: '800'
minWidth: '470'
height: '500'
minHeight: '450'
active: true
multipleInstances: false
restrictAccess: false
resizable: true
draggable: true
closable: true
minimizable: true
maximizable: true
system: false
showTitle: true
proxyAppUrl: '/pubsubUserProfile/'
proxyAppPath: '/pubsubUserProfile/**'
version: '3.0.0-SNAPSHOT'
lexicon:
  - languageLocale: en
    values:
      - key: title
        value: Pub/Sub User Profile
      - key: description
        value: Application which receives the user information through a QPubSub channel.
  - languageLocale: el
    values:
      - key: title
        value: Pub/Sub Προφίλ Χρήστη
      - key: description
        value: Εφαρμογή η οποία λαμβάνει τις πληροφορίες του χρήστη μέσω ενός καναλιού του QPubSub.